version: '3'

services:
  

  docker-registry:
    image: registry:2
    depends_on:
      - traefik
    networks:
      - gateway
    volumes:
      - /opt/registry:/var/lib/registry
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=registry"
      - "traefik.frontend.rule=Host:docker.syncify.me"
      - "traefik.port=5000"
    deploy:
      restart_policy:
        condition: any

  new-api:
      image: docker.syncify.me/news-api:latest
      networks: 
        - gateway
      labels:
        - "traefik.enabled=true"
        - "traefik.backend=new-api"
        - "traefik.frontend.rule=Host:www.syncify.me"
        - "traefik.port=8080"
      deploy:
        restart_policy:
          condition: any

networks:
  gateway:
    driver: overlay
    external: true