version: "3"

services:
  prom:
    image: prom/prometheus:v2.1.0
    volumes:
      - /opt/traefik/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - gateway
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=prometheus-prom"
      - "traefik.frontend.rule=Host:monitor.syncify.me;PathPrefixStrip:/docker-monitor"
      - "traefik.port=9090"
    deploy:
      restart_policy:
        condition: any
networks:
  gateway:
    driver: overlay
    external: true
