version: "3"

services:
  prom:
    image: prom/prometheus:v2.1.0
    volumes:
      - /opt/traefik/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - gateway
    labels:
        - "traefik.enabled=true"
        - "traefik.backend=prometheus-prom"
        - "traefik.frontend.rule=Host:monitor.syncify.me;PathPrefix:/docker-monitor"
        - "traefik.port=9090"
      deploy:
        restart_policy:
          condition: any
    
    depends_on:
      - exporter
  exporter:
    image: prom/node-exporter:latest
    networks:
      - gateway
    
#    network_mode: host
  grafana:
    image: grafana/grafana
    networks:
      - gateway
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=prometheus-grafana"
      - "traefik.frontend.rule=Host:monitor.syncify.me;PathPrefix:/grafana-monitor"
      - "traefik.port=3000"
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - prom

networks:
  gateway:
    driver: overlay
    external: true
