version: '3'

services:
  traefik:
    image: traefik:1.6.0
    command: --web --docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
      - /var/log/traefik.log:/var/log/traefik.log
      - /var/log/access.log:/var/log/access.log
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:monitor.syncify.me"
      - "traefik.port=8080"
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

  docker-registry:
    image: registry:2
    depends_on:
      - traefik
    networks:
      - web
    volumes:
      - /opt/registry:/var/lib/registry
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=registry"
      - "traefik.frontend.rule=Host:docker.syncify.me"
      - "traefik.port=5000"
    deploy:
      restart_policy:
        condition: any

  new-api:
      image: docker.syncify.me/news-api:latest
      networks: 
        - web
      labels:
        - "traefik.enabled=true"
        - "traefik.backend=new-api"
        - "traefik.frontend.rule=Host:www.syncify.me"
        - "traefik.port=8080"
      deploy:
        restart_policy:
          condition: any

networks:
  web:
    driver: overlay