version: '2'

services:
  traefik:
    image: traefik:1.6.2
    command: --web --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:monitor.syncify.me"
      - "traefik.port=8080"
    container_name: traefik

  docker-registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - traefik
    networks:
      - web
    volumes:
      - /opt/registry:/var/lib/registry
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=registry"
      - "traefik.frontend.rule=Host:docker.syncify.me"
      - "traefik.port=5000"

networks:
  web:
    external: true
