version: "3"

services:
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - /opt/traefik/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    labels:
        - "traefik.enabled=true"
        - "traefik.backend=promeheus-prom"
        - "traefik.frontend.rule=Host:monitor.syncify.me;PathPrefix:/docker-monitor"
        - "traefik.port=9090"
      deploy:
        restart_policy:
          condition: any
    
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
#    network_mode: host
  grafana:
    image: grafana/grafana
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=promeheus-prom"
      - "traefik.frontend.rule=Host:monitor.syncify.me;PathPrefix:/grafana-monitor"
      - "traefik.port=3000"
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - prom