debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[traefikLog]
  filePath = "/var/log/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    regex = "^http://www.syncify.me/(.*)"
    replacement = "https://www.syncify.me/$1"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

# Metrics definition
[metrics]
  #...

  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]

    # Name of the related entry point
    #
    # Optional
    # Default: "traefik"
    #
    entryPoint = "traefik"

    # Buckets for latency metrics
    #
    # Optional
    # Default: [0.1, 0.3, 1.2, 5]
    #
    buckets = [0.1,0.3,1.2,5.0]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "syncify.me"
watch = true
swarmmode = true
exposedbydefault = false

[acme]
email = "pandey.adarsh147@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[[acme.domains]]
  main = "syncify.me"
  sans = ["www.syncify.me", "monitor.syncify.me", "docker.syncify.com"]
[acme.httpChallenge]
entryPoint = "http"
